version: '3'

services:

  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: super_secret_pass
      POSTGRES_DB: ts-orm
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - ts-orm-data:/var/lib/postgresql/data


volumes:
  ts-orm-data:
    external: false
